name: eventsource
description: A client and server implementation of Server-Sent Events.
version: 0.5.0
homepage: https://github.com/stevenroose/dart-eventsource

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  collection: ^1.15.0
  http: ^1.2.2
  http_parser: ^4.0.0
  logging: ^1.0.1
  sync: ^0.3.0

dev_dependencies:
  lints: ^4.0.0
  test: ^1.17.11
